<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QRCoder" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../AlIkhsanMedia.Drone.Core/AlIkhsanMedia.Drone.Core.csproj" />
  </ItemGroup>

</Project>
